spring.application.name=fleet-service
server.port=8081

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/autocare_fleet
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true